### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by aarondr77** [Great-Hill-Corporation/daodeepdive#3]
At the top of this page is says "(click on a question to expand the answer)," but all the answers are automatically displayed when the page is loaded and clicking on the questions makes no change. 

Answer number 3, Sentence number 2: "Allowing unlimited topics leads to discussion bloat and a totaly inability to actually learn anything?" You should replace the word "totally" with "total"

Anser number 4, Sentence number 3: "Many non-technical people seem to think that their questions are the most important thing in the world, and barge right in to a conversation." You should delete the space between the words "in to" and make it read "into."

**Comment by tjayrush** [comment]
I took off the FAQ page for now.
