### ISSUE TITLE
About

### ISSUE THREAD

**Issue by aarondr77** [Great-Hill-Corporation/daodeepdive#4]
In the third paragraph of "Who Are We?" a sentence reads, "Many of our clients are still with us--20 years later--this is a testement to our manaical attention to detail." I think you should change this to "Many of our clients are still with us 20 years later; this is a testament to our maniacal attention to detail" 

In the second paragraph of "Full Privacy Policy," a sentence reads, "We use this information for the operation of the site and to periodically email information about the our projects." You should delete the third to last word ('the') from this sentence. In the next sentence "Users may opt-out of receiving future mailings; see below." You should replace (;) with a (-).

**Comment by tjayrush** [comment]
Done.
