### ISSUE TITLE
Some Ideas... 

### ISSUE THREAD

**Issue by aarondr77** [Great-Hill-Corporation/daodeepdive#5]
Once the discussion board is running, in the "My account" link at the top of the page, you could have a spot where users can keep track of the discussions they have participated in. People could get notifications when someone replies to their comment in the discussion group

I have a few ideas about questions people might want answered. I'm not sure that they necessarily fit into the theme of this website, but maybe they could fit on one of your other websites: 

1. How much Ether exists?
2. Where is all the Ether? As in, how much of it is in the Dao? How much of it is simply just in someone’s wallet as Ether not tokens?
3. Where are people spending Ether? Are any stores accepting Ether yet? 
4. What determines the price of Ether relative to USD? Supply and demand —> does that mean there is a fixed amount of ether?
5. Have people been buying Ether from the originator of it and then once all of the originator’s ether is gone people buy it from each other and that determines the price?
6. What has been the result of votes on the Dao? (I know voting hasn't started yet, but when it does)
7. How do I propose a vote in the Dao? How do I vote? How many tokens are in the Dao? 
8. How  am I going to make money from the Dao? When we, as a collective Dao, vote to give someone money, how do I get money back? Is my money awarded to my mist wallet, do I get more tokens, or does it simply effect the "stock price" of the Dao?
9. How many communities like The Dao exist? Why should I invest in The Dao as opposed to other contracts? What other contracts exist? Where can I find them?

**Comment by tjayrush** [comment]
These are excellent questions. I copied them into my source code but put them in a comment. I will revisit each of these later.

**Comment by tjayrush** [comment]
I'm going to close this for now, since I copied it into code.
